---
:source:
  :path: test
  :file: test_sum.c
:successes: []
:failures:
- :test: test_sum_read_space_with_5_as_5
  :line: 20
  :message: Element 0 Expected 5 Was 0. Function get_number Argument result. Function
    called with unexpected argument value.
  :unity_test_time: 0
:ignores: []
:counts:
  :total: 1
  :passed: 0
  :failed: 1
  :ignored: 0
:stdout: []
:time: 0.01227659999858588
